### ISSUE TITLE
10分钟看懂动态代理设计模式（升级篇）疑问

### ISSUE THREAD

**Issue by zhangxianwen2** [yuanhoujun/java-dynamic-proxy#1]
作者您好，首先非常感谢您的分享。
刚刚读到这篇文章的前半部分，有一个比较疑问的点，最开始的例子：朋友是代理应该反了吗，看代码感觉朋友是被代理对象才对。
刚刚开始学习这个模式，所以心里没底，希望作者能够解答一下，不胜感激。

**Comment by yuanhoujun** [comment]
对，表述不太清楚，不好意思



---原始邮件---
发件人: "Z-SEVEN"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 晚上11:18
收件人: "yuanhoujun/java-dynamic-proxy"<java-dynamic-proxy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yuanhoujun/java-dynamic-proxy] 10分钟看懂动态代理设计模式（升级篇）疑问 (#1)




 
作者您好，首先非常感谢您的分享。
 刚刚读到这篇文章的前半部分，有一个比较疑问的点，最开始的例子：朋友是代理应该反了吗，看代码感觉朋友是被代理对象才对。
 刚刚开始学习这个模式，所以心里没底，希望作者能够解答一下，不胜感激。

**Comment by zhangxianwen2** [comment]
感谢您的答复，这对我接下去的理解十分重要
